### ISSUE TITLE
`live`: <class 'bumpy.float32'> rejected; `Keras` breaks if `lr` included metric in callback

### ISSUE THREAD

**Issue by bobertlo** [iterative/dvclive#253]
The Keras callback works really well, but as soon as I started using the ReduceLROnPlateau, the learning rate gets added to the metrics, and this crashes the program and prevents my model from training. 

```
Traceback (most recent call last):
  File "train.py", line 80, in <module>
    model.fit(train_gen,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf-metal/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf-metal/lib/python3.8/site-packages/dvclive/keras.py", line 42, in on_epoch_end
    self.dvclive.log(metric, value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf-metal/lib/python3.8/site-packages/dvclive/live.py", line 142, in log
    raise InvalidDataTypeError(name, type(val))
dvclive.error.InvalidDataTypeError: Data 'lr' has not supported type <class 'numpy.float32'>
ERROR: failed to reproduce 'train': failed to run: python train.py, exited with 1
```

I found that if I added:

```
if isinstance(val, np.float32):
    val = float(val)
```

to live.py right before:

https://github.com/iterative/dvclive/blob/9602d7fcbbf8e7224c591faece95d43aae89234b/dvclive/live.py#L141-L142

this was solved, but I am not familiar with this codebase and I am not sure this is a satisfactory solution.

**Comment by daavoo** [comment]
Thanks for the report @bobertlo . #254 should fix this

**Comment by bobertlo** [comment]
Thank you!
