### ISSUE TITLE
Notebook report generates 404 if running multiple experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#537]
When running the example-get-started-experiments notebook, the report from the previous experiment is replaced by a 404 once the next experiment in the loop starts:

https://user-images.githubusercontent.com/2308172/233172524-0573eab5-7aef-4220-acaa-d85a672d1ebe.mov

**Comment by dberenbaum** [comment]
Not sure if I should open another issue for this, but I also don't see any notebook report when using VS Code:

<img width="1083" alt="Screenshot 2023-04-24 at 8 20 30 PM" src="https://user-images.githubusercontent.com/2308172/234143552-cc38bc2d-ff7f-4535-bc23-10d7227b37a0.png">

**Comment by daavoo** [comment]
> Not sure if I should open another issue for this, but I also don't see any notebook report when using VS Code:
> 
> <img alt="Screenshot 2023-04-24 at 8 20 30 PM" width="1083" src="https://user-images.githubusercontent.com/2308172/234143552-cc38bc2d-ff7f-4535-bc23-10d7227b37a0.png">

@dberenbaum is this in Codespaces? 
Anyhow, yes, should probably be a separate issue

**Comment by kshitiz305** [comment]
@dberenbaum  could you provide me the code to replicate the issue in my system?

**Comment by dberenbaum** [comment]
@kshitiz305 The code is available in https://github.com/iterative/example-get-started-experiments/

**Comment by kshitiz305** [comment]
@dberenbaum Please assist me with how shall I solve this. it is giving me the error


```
Traceback (most recent call last):
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/add.py", line 87, in translate_graph_error
    yield
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/add.py", line 176, in add
    repo.check_graph(
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/__init__.py", line 286, in check_graph
    new.check_graph()
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/index.py", line 274, in check_graph
    self.graph  # noqa: B018, pylint: disable=pointless-statement
  File "/home/ks/.local/lib/python3.10/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/index.py", line 270, in graph
    return build_graph(self.stages, self.outs_trie)
  File "/home/ks/.local/lib/python3.10/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/index.py", line 258, in outs_trie
    return build_outs_trie(self.stages)
  File "/home/ks/.local/lib/python3.10/site-packages/dvc/repo/trie.py", line 17, in build_outs_trie
    raise OutputDuplicationError(str(out), dup_stages)
    
dvc.exceptions.OutputDuplicationError: output '../models/model.pkl' is already specified in stage: '../dvc.yaml:train'.
Use `dvc remove ../dvc.yaml:train` to stop tracking the overlapping output.
```

**Comment by kshitiz305** [comment]
The is further an exception 

```
"dvc.exceptions.OutputDuplicationError: output '../models/model.pkl' is already specified in stages:
	- ../dvc.yaml:train
	- ../models/model.pkl.dvc
Use `dvc remove ../dvc.yaml:train ../models/model.pkl.dvc` to stop tracking the overlapping output.
```"

**Comment by dberenbaum** [comment]
@kshitiz305 That exception should be caught by the code there, right? It's expected and should only raise a warning. It's happening because `models/model.pkl.dvc` is [already tracked as an output in the dvc pipeline](https://github.com/iterative/example-get-started-experiments/blob/dd9c2f643f80016bbb36c10289631306041e3c5e/dvc.yaml#L22) and dvclive tries to `dvc add` the same path, which dvc doesn't allow.

**Comment by dberenbaum** [comment]
@kshitiz305 You can ignore the warning and do nothing. The output is being tracked already, so no further action is needed.

**Comment by kshitiz305** [comment]
@dberenbaum is there any other way the error of 404 can be solved?

**Comment by daavoo** [comment]
For the record, I took a quick look.

The previous cell output can be cleaned with `IPython.display.clear_output`:

```py
import time
from dvclive import Live
from IPython.display import clear_output

for i in range(3):
    with Live(report="notebook") as live:
        for j in range(2):
            live.log_metric("foo", j)
            live.next_step()
            time.sleep(1)
    clear_output(wait=True)
```

However, this cleans the full cell output not just the DVCLive HTML. 
I didn't look into how to clean out only that.

@dberenbaum Do you think we should just document this or invest in making this happen under the hood and cleaning only the HTML? Is the `for` loop a realistic scenario or just something we use in our examples?

**Comment by dberenbaum** [comment]
Discussed with @daavoo that it would be better to enlist help from other teams more familiar with frontend web dev to help with rendering the html report.

@daavoo What do you think about using markdown in the notebooks at least temporarily? It would probably be simpler, although it requires matplotlib.
